INSERT INTO pvuv_sink
SELECT
  DATE_FORMAT(TO_TIMESTAMP(CAST(ts as VARCHAR)), 'yyyy-MM-dd HH:00') dt,
  COUNT(*) AS pv,
  COUNT(DISTINCT user_id) AS uv
FROM user_log
GROUP BY DATE_FORMAT(TO_TIMESTAMP(CAST(ts as VARCHAR)), 'yyyy-MM-dd HH:00');
